<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poc.proto

namespace GPBMetadata;

class Poc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
?
	poc.protopoc"%

PocMessage

id (
txt (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

